### ISSUE TITLE
Doesn't Seem to Work with the new EA App

### ISSUE THREAD

**Issue by VinceyG** [just-harry/tiny-ui-fix-for-ts3#6]
With the switch from Origine to the EA App, finding the path isn't done automatically. Which isn't exactly a problem, except for the fact that I've tried for an hour now and I can't get it to recognize the The Sims 3 folder. For whatever reason, it never understands that the Sims 3 is in the EA Games app. Thanks.

**Comment by ramirocantu** [comment]
On Mac you can find the folder here: /Applications/EA Games/Sims3Launcher.app/Contents/Resources/The Sims 3.app/

**Comment by just-harry** [comment]
Thanks for alerting me of this, and so, sorry for taking so long to do anything about it.
I've just released v1.4.0 of the mod, which should properly support EA App installations of the game, on macOS.

I'm going to close this issue, but please feel free to reopen it should v1.4.0 not actually fix it.
